In [1]:
import pandas as pd
import numpy as np
import pickle

In [4]:
stocks = pd.read_pickle('data/stock_code.pkl')

In [5]:
stock = stocks['stock'].values[0]

In [6]:
stock

'000001.XSHE'

In [19]:
data = pd.read_pickle('data/' + str(stock) + '.pkl')

In [10]:
data

,open,close,low,high,volume,money,factor,high_limit,low_limit,avg,pre_close,paused
2023-11-30,8.85,8.84,8.79,8.89,98730879.0,8.714817e+08,0.913356,9.76,7.99,8.83,8.88,0.0
2023-12-01,8.81,8.82,8.75,8.84,85186592.0,7.496684e+08,0.913356,9.73,7.96,8.80,8.84,0.0
2023-12-04,8.83,8.80,8.78,8.84,66287158.0,5.836643e+08,0.913356,9.71,7.94,8.80,8.82,0.0
2023-12-05,8.78,8.66,8.65,8.79,86207167.0,7.509612e+08,0.913356,9.67,7.92,8.71,8.80,0.0
2023-12-06,8.62,8.68,8.59,8.74,82449317.0,7.140295e+08,0.913356,9.53,7.79,8.66,8.66,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
2024-12-02,11.39,11.39,11.31,11.40,97543366.0,1.108786e+09,1.000000,12.52,10.24,11.37,11.38,0.0
2024-12-03,11.37,11.49,11.35,11.50,108255936.0,1.236993e+09,1.000000,12.53,10.25,11.43,11.39,0.0
2024-12-04,11.44,11.46,11.37,11.53,100747059.0,1.154623e+09,1.000000,12.64,10.34,11.46,11.49,0.0
2024-12-05,11.44,11.44,11.41,11.50,68710883.0,7.861380e+08,1.000000,12.61,10.31,11.44,11.46,0.0
2024-12-06,11.44,11.66,11.43,11.70,172626927.0,2.004270e+09,1.000000,12.58,10.30,11.61,11.44,0.0

In [11]:
data = data[data['paused'] == 0]

In [12]:
data

,open,close,low,high,volume,money,factor,high_limit,low_limit,avg,pre_close,paused
2023-11-30,8.85,8.84,8.79,8.89,98730879.0,8.714817e+08,0.913356,9.76,7.99,8.83,8.88,0.0
2023-12-01,8.81,8.82,8.75,8.84,85186592.0,7.496684e+08,0.913356,9.73,7.96,8.80,8.84,0.0
2023-12-04,8.83,8.80,8.78,8.84,66287158.0,5.836643e+08,0.913356,9.71,7.94,8.80,8.82,0.0
2023-12-05,8.78,8.66,8.65,8.79,86207167.0,7.509612e+08,0.913356,9.67,7.92,8.71,8.80,0.0
2023-12-06,8.62,8.68,8.59,8.74,82449317.0,7.140295e+08,0.913356,9.53,7.79,8.66,8.66,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
2024-12-02,11.39,11.39,11.31,11.40,97543366.0,1.108786e+09,1.000000,12.52,10.24,11.37,11.38,0.0
2024-12-03,11.37,11.49,11.35,11.50,108255936.0,1.236993e+09,1.000000,12.53,10.25,11.43,11.39,0.0
2024-12-04,11.44,11.46,11.37,11.53,100747059.0,1.154623e+09,1.000000,12.64,10.34,11.46,11.49,0.0
2024-12-05,11.44,11.44,11.41,11.50,68710883.0,7.861380e+08,1.000000,12.61,10.31,11.44,11.46,0.0
2024-12-06,11.44,11.66,11.43,11.70,172626927.0,2.004270e+09,1.000000,12.58,10.30,11.61,11.44,0.0

In [20]:
data[['open', 'close', 'low', 'high', 'avg']] = data[['open', 'close', 'low', 'high', 'avg']].sub(data['pre_close'], axis=0).div(data['pre_close'], axis=0)

In [21]:
data

,open,close,low,high,volume,money,factor,high_limit,low_limit,avg,pre_close,paused
2023-11-30,-0.003378,-0.004505,-0.010135,0.001126,98730879.0,8.714817e+08,0.913356,9.76,7.99,-0.005631,8.88,0.0
2023-12-01,-0.003394,-0.002262,-0.010181,0.000000,85186592.0,7.496684e+08,0.913356,9.73,7.96,-0.004525,8.84,0.0
2023-12-04,0.001134,-0.002268,-0.004535,0.002268,66287158.0,5.836643e+08,0.913356,9.71,7.94,-0.002268,8.82,0.0
2023-12-05,-0.002273,-0.015909,-0.017045,-0.001136,86207167.0,7.509612e+08,0.913356,9.67,7.92,-0.010227,8.80,0.0
2023-12-06,-0.004619,0.002309,-0.008083,0.009238,82449317.0,7.140295e+08,0.913356,9.53,7.79,0.000000,8.66,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
2024-12-02,0.000879,0.000879,-0.006151,0.001757,97543366.0,1.108786e+09,1.000000,12.52,10.24,-0.000879,11.38,0.0
2024-12-03,-0.001756,0.008780,-0.003512,0.009658,108255936.0,1.236993e+09,1.000000,12.53,10.25,0.003512,11.39,0.0
2024-12-04,-0.004352,-0.002611,-0.010444,0.003481,100747059.0,1.154623e+09,1.000000,12.64,10.34,-0.002611,11.49,0.0
2024-12-05,-0.001745,-0.001745,-0.004363,0.003490,68710883.0,7.861380e+08,1.000000,12.61,10.31,-0.001745,11.46,0.0
2024-12-06,0.000000,0.019231,-0.000874,0.022727,172626927.0,2.004270e+09,1.000000,12.58,10.30,0.014860,11.44,0.0

In [ ]:
data = data[['open', 'close', 'low', 'high', 'volumne', 'factor', 'avg']]

In [13]:
test = pd.read_pickle('data/000002.XSHE.pkl')

In [22]:
import os
if os.path.exists('data/000002.XSHE.pkl'):
    print('hh')

hh

In [ ]:
data[]

In [14]:
test

,open,close,low,high,volume,money,factor,high_limit,low_limit,avg,pre_close,paused
2023-11-30,11.41,11.44,11.40,11.55,38831587.0,4.455959e+08,1.0,12.61,10.31,11.48,11.46,0.0
2023-12-01,11.44,11.40,11.28,11.53,66540336.0,7.572202e+08,1.0,12.58,10.30,11.38,11.44,0.0
2023-12-04,11.35,11.18,11.16,11.40,70053432.0,7.864015e+08,1.0,12.54,10.26,11.23,11.40,0.0
2023-12-05,11.16,10.79,10.78,11.16,95008617.0,1.038469e+09,1.0,12.30,10.06,10.93,11.18,0.0
2023-12-06,10.79,10.85,10.66,10.93,61763481.0,6.673583e+08,1.0,11.87,9.71,10.80,10.79,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
2024-12-02,8.53,8.68,8.52,8.73,108741356.0,9.401748e+08,1.0,9.46,7.74,8.65,8.60,0.0
2024-12-03,8.65,8.74,8.60,8.78,117281518.0,1.017984e+09,1.0,9.55,7.81,8.68,8.68,0.0
2024-12-04,8.70,8.55,8.53,8.70,110173644.0,9.482501e+08,1.0,9.61,7.87,8.61,8.74,0.0
2024-12-05,8.50,8.52,8.45,8.54,73343506.0,6.229269e+08,1.0,9.41,7.70,8.49,8.55,0.0
2024-12-06,8.51,8.68,8.48,8.72,130103582.0,1.123618e+09,1.0,9.37,7.67,8.64,8.52,0.0